### ISSUE TITLE
Exception: Unable to detect format from ['SNV;ENSG00000225630', '1', '+', '50', '0']

### ISSUE THREAD

**Issue by WYSNI** [bioinform/rnacocktail#12]
Hi, 

First thanks for this very complete pipeline.

I have a problem with the step 5 of the editing mode. 

![error](https://user-images.githubusercontent.com/27208245/46863738-74dd5780-ce18-11e8-9fb5-a89268182742.png)

I think the problem is in line 88 of the editing.py file and more precisely on the merge_info_SNV function.

![image](https://user-images.githubusercontent.com/27208245/46862932-57a78980-ce16-11e8-8dfd-8fb28e48033a.png)

The exception is raised in line 90 of this file because (I think again), the cat() function is not possible between SNV_fwd and SNV_fwd1.

This is a capture of the SNV_no var:

![image](https://user-images.githubusercontent.com/27208245/46864606-2b423c00-ce1b-11e8-8fef-d4dda23ce884.png)

a capture of the "feature" var on the  merge_info_SNV function:

![image](https://user-images.githubusercontent.com/27208245/46864981-30ec5180-ce1c-11e8-8730-94f49cf805db.png)

and of my vcf file : 

![image](https://user-images.githubusercontent.com/27208245/46864809-b9b6bd80-ce1b-11e8-9be8-cc7d8c87ddf8.png)

Do you have any idea of what's going on?

Thanks!

**Comment by msahraeian** [comment]
@WYSNI Happy to see your interest in RNACocktail. Would you please let me know what version of bedtools and pybedtools you are using?

**Comment by WYSNI** [comment]
I'm using pybedtools 0.7.7 and bedtools 2.26.0 on a conda environment. Is it a bedtools version problem in your opinion?

**Comment by msahraeian** [comment]
@WYSNI I recall bedtools 2.26.0 had some issues with `groupby`. Would you please use later versions of bedtools like 2.27 ?

**Comment by WYSNI** [comment]
It's works! Thanks a lot 

![image](https://user-images.githubusercontent.com/27208245/47006976-7a4be200-d137-11e8-930e-c386c005b1c9.png)


I don't understand why GIREMI return a 1 code in steps 6 and 9 despite I have giremi_out.txt.res and it seems good

giremi_out.txt.res

![image](https://user-images.githubusercontent.com/27208245/46942919-ab141480-d06e-11e8-9fbc-ce29f156bf2b.png)

giremi.log
![image](https://user-images.githubusercontent.com/27208245/47006769-f8f44f80-d136-11e8-90ea-c99a07543e8a.png)


Any idea?

**Comment by msahraeian** [comment]
@WYSNI the first return code of 1 is normal, as we do it in two iterations. For the second one you can check the `giremi.log` file at `work/giremi/A` for more specific logs. In my experience as long as `giremi_out.txt.res` exists and has the `ifRNA` column the predictions should be OK. You can also check whether `giremi_out.txt.res` covers all your region. Also, check how many `1`'s you have in the `if RNA` (last) column.

**Comment by WYSNI** [comment]
Ok Thanks! I have some "1" in my ifRNAE column so I think the result is ok.
Last question: can I used files on the test directory ( GRCh37_genes_pos.bed.gz, GRCh37_strand_pos.bed.gz, GRCh38_genes_pos.bed.gz, GRCh38_strand_pos.bed.gz) for my experiments or are they not complete ?

**Comment by msahraeian** [comment]
@WYSNI Yes they are complete for whole genome GRCh37 and GRCh38 references.

**Comment by WYSNI** [comment]
Thanks a lot!

I close this issue.

**Comment by WYSNI** [comment]
Hi, 

Sorry, I reopen this issue because I have another problem with the step 5 of the editing mode...

![image](https://user-images.githubusercontent.com/27208245/47294766-462c6180-d60e-11e8-9759-9d8229602222.png)

I think the problem is again in line 88 of the editing.py file but with the groupby now.

I'm on a conda environment with bedtools 2.27.1 and pybedtools 0.7.7.
My environment (RNACocktail) path is in the first place of my $PATH:

![image](https://user-images.githubusercontent.com/27208245/47295230-732d4400-d60f-11e8-945a-22c51985b183.png)

I don't understand what's going on! 
Any suggestion?

Thanks, WYSNI

**Comment by WYSNI** [comment]
Ok my bad, it's just a problem of chromosome name on GRCh38 files of the test/ repository.

Sorry!

I (re)closed this issue.
