### ISSUE TITLE
Variant Calling

### ISSUE THREAD

**Issue by jerryguintivano** [bioinform/rnacocktail#13]
Hello!

I am working to use rnacocktail to call variants in my data (following alignment using HISAT2). I have run into the following error:

> INFO  10:17:19,797 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 
> INFO  10:17:19,797 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
> INFO  10:17:19,797 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 
> INFO  10:17:19,797 HelpFormatter - [Thu Feb 14 10:17:19 EST 2019] Executing on Linux 3.10.0-957.el7.x86_64 amd64 
> INFO  10:17:19,797 HelpFormatter - OpenJDK 64-Bit Server VM 1.8.0_191-b12 
> INFO  10:17:19,800 HelpFormatter - Program Args: -T HaplotypeCaller -R Homo_sapiens.GRCh37.dna.primary_assembly.fa -I working/gatk/MHXXXXXXX-XXXXXXXXXX/bsqr.bam -o working/gatk/MHXXXXXXX-XXXXXXXXXX/variants.vcf -stand_call_conf 20.000000 -stand_emit_conf 20.000000 -dontUseSoftClippedBases 
> INFO  10:17:19,808 HelpFormatter - Executing as XXXXXX@XXXXXX on Linux 3.10.0-957.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_191-b12. 
> INFO  10:17:19,809 HelpFormatter - Date/Time: 2019/02/14 10:17:19 
> INFO  10:17:19,809 HelpFormatter - ---------------------------------------------------------------------------------- 
> INFO  10:17:19,809 HelpFormatter - ---------------------------------------------------------------------------------- 
> ##### ERROR ------------------------------------------------------------------------------------------
> ##### ERROR A USER ERROR has occurred (version 3.8-0-ge9d806836): 
> ##### ERROR
> ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
> ##### ERROR The error message below tells you what is the problem.
> ##### ERROR
> ##### ERROR If the problem is an invalid argument, please check the online documentation guide
> ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
> ##### ERROR
> ##### ERROR Visit our website and forum for extensive documentation and answers to 
> ##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
> ##### ERROR
> ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
> ##### ERROR
> ##### ERROR MESSAGE: Invalid command line: The parameter standard_min_confidence_threshold_for_emitting is deprecated.  This argument is no longer used in GATK versions 3.7 and newer. Please see the online documentation for the latest usage recommendations.

Does rnacocktail only support GATK version 3.5? 

Thanks so much for your help!

**Comment by msahraeian** [comment]
@jerryguintivano 
Happy to see your interest in RNACocktail.
Currently RNACocktail supports GATK 3.5. You can find that version at:
https://software.broadinstitute.org/gatk/download/archive
https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.5-0-g36282e4

**Comment by msahraeian** [comment]
@jerryguintivano 
We have upgraded tools to latest version at #17  (GATK 4 is also supported now).
The new docker image (v0.3.0) have these tools pre-installed.
