### ISSUE TITLE
GIREMI failed!

### ISSUE THREAD

**Issue by 815325223** [bioinform/rnacocktail#14]
I‘m getting some errors with the following command, I hope to help solve it, thank you very much.
-------------------------------------------------------------------------------------------------------------------
$ docker run --rm -u container_R -v /D8:/data -v /Container:/write rnacocktail:latest run_rnacocktail.py editing --alignment /data/D8.sorted.bam --variant /data/D8.snv.vcf --strand_pos /data/hg19_strand_pos.bed --genes_pos /data/hg19_genes_pos.bed --outdir /write/out --workdir /write/work --threads 10 --sample D8 --ref_genome /data/Homo_sapiens.GRCh37.dna.primary_assembly.fa --knownsites /data/common_all_20180418.vcf --giremi_dir /usr/local/bin/
-------------------------------------------------------------------------------------------------------------------
INFO 2019-02-27 09:02:18,708 src.utils            Running RNASeqPipeline 0.2.2
INFO 2019-02-27 09:02:18,708 src.utils            Command-line /usr/local/bin/run_rnacocktail.py editing --alignment /data/D8.sorted.bam --variant /data/D8.snv.vcf --strand_pos /data/hg19_strand_pos.bed --genes_pos /data/hg19_genes_pos.bed --outdir /write/out --workdir /write/work --threads 10 --sample D8 --ref_genome /data/Homo_sapiens.GRCh37.dna.primary_assembly.fa --knownsites /data/common_all_20180418.vcf --giremi_dir /usr/local/bin/ --htslib_dir=/opt/htslib-1.3/
INFO 2019-02-27 09:02:18,708 src.utils            Arguments are Namespace(VariantAnnotator_opts='', alignment='/data/D8.sorted.bam', editing_caller='GIREMI', gatk='GenomeAnalysisTK.jar', genes_pos='/data/hg19_genes_pos.bed', giremi_dir='/usr/local/bin/', giremi_opts='', htslib_dir='/opt/htslib-1.3/', java='java', java_opts='-Xms1g -Xmx5g', knownsites='/data/common_all_20180418.vcf', mode='editing', outdir='/write/out', ref_genome='/data/Homo_sapiens.GRCh37.dna.primary_assembly.fa', sample='D8', samtools='samtools', start=0, strand_pos='/data/hg19_strand_pos.bed', threads=10, timeout=10000000, variant='/data/D8.snv.vcf', workdir='/write/work')
INFO 2019-02-27 09:02:18,709 src.utils            Run log will be saved in /write/work/logs/run-editing-20190227-090218.log
INFO 2019-02-27 09:02:18,709 src.utils            Run in mode: editing
INFO 2019-02-27 09:02:18,709 src.utils            Running RNA editing calling step using GIREMI
INFO 2019-02-27 09:02:18,709 src.run_editing      Running RNA editing detection (GIREMI) for D8
ERROR 2019-02-27 09:02:18,710 src.run_editing      Aborting!
INFO 2019-02-27 09:02:18,710 src.run_editing      GIREMI failed!
ERROR 2019-02-27 09:02:18,710 src.run_editing      No alignment file /data/D8.sorted.bam

**Comment by msahraeian** [comment]
@815325223 happy to see your interest in RNACocktail. 
I guess your volumes are not mounted correctly to the docker image. Can you try to mount to /work_dir/data and /work_dir/work instead.

**Comment by 815325223** [comment]
@msahraeian I don't think I have a mount problem. I tried using your mount path.
# run_rnacocktail.py editing --alignment /work_dir/data/D8.sorted.bam --variant /work_dir/data/D8.snv.vcf --strand_pos /work_dir/data/hg19_strand_pos.bed --genes_pos /work_dir/data/hg19_genes_pos.bed --outdir /work_dir/work --workdir /work_dir/work --threads 10 --sample D8 --ref_genome /work_dir/data/Homo_sapiens.GRCh37.dna.primary_assembly.fa --knownsites /work_dir/data/common_all_20180418.vcf --giremi_dir /user/local/bin/
INFO 2019-03-04 01:47:46,022 src.utils            Running RNASeqPipeline 0.2.2
INFO 2019-03-04 01:47:46,023 src.utils            Command-line /usr/local/bin/run_rnacocktail.py editing --alignment /work_dir/data/D8.sorted.bam --variant /work_dir/data/D8.snv.vcf --strand_pos /work_dir/data/hg19_strand_pos.bed --genes_pos /work_dir/data/hg19_genes_pos.bed --outdir /work_dir/work --workdir /work_dir/work --threads 10 --sample D8 --ref_genome /work_dir/data/Homo_sapiens.GRCh37.dna.primary_assembly.fa --knownsites /work_dir/data/common_all_20180418.vcf --giremi_dir /user/local/bin/
INFO 2019-03-04 01:47:46,023 src.utils            Arguments are Namespace(VariantAnnotator_opts='', alignment='/work_dir/data/D8.sorted.bam', editing_caller='GIREMI', gatk='GenomeAnalysisTK.jar', genes_pos='/work_dir/data/hg19_genes_pos.bed', giremi_dir='/user/local/bin/', giremi_opts='', htslib_dir='', java='java', java_opts='-Xms1g -Xmx5g', knownsites='/work_dir/data/common_all_20180418.vcf', mode='editing', outdir='/work_dir/work', ref_genome='/work_dir/data/Homo_sapiens.GRCh37.dna.primary_assembly.fa', sample='D8', samtools='samtools', start=0, strand_pos='/work_dir/data/hg19_strand_pos.bed', threads=10, timeout=10000000, variant='/work_dir/data/D8.snv.vcf', workdir='/work_dir/work')
INFO 2019-03-04 01:47:46,023 src.utils            Run log will be saved in /work_dir/work/logs/run-editing-20190304-014746.log
INFO 2019-03-04 01:47:46,023 src.utils            Run in mode: editing
INFO 2019-03-04 01:47:46,023 src.utils            Running RNA editing calling step using GIREMI
INFO 2019-03-04 01:47:46,023 src.run_editing      Running RNA editing detection (GIREMI) for D8
ERROR 2019-03-04 01:47:46,024 src.run_editing      Aborting!
INFO 2019-03-04 01:47:46,024 src.run_editing      GIREMI failed!
ERROR 2019-03-04 01:47:46,024 src.run_editing      No alignment file /work_dir/data/D8.sorted.bam
Traceback (most recent call last):
  File "/usr/local/bin/run_rnacocktail.py", line 931, in <module>
    sys.exit(run_pipeline(args,parser))
  File "/usr/local/lib/python2.7/dist-packages/src/main.py", line 242, in run_pipeline
    workdir=args.workdir, outdir=args.outdir, timeout=args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/src/run_editing.py", line 372, in run_editing
    raise Exception(excp)
Exception: No alignment file /work_dir/data/D8.sorted.bam

**Comment by msahraeian** [comment]
It seems that your bam is not visible to the code.
Can you check you have your bam in your local machine at `/D8/D8.sorted.bam` and you can see that when you load it to docker using:
`docker run --rm -u container_R -v /D8:/work_dir/data -v /Container:/work_dir/write rnacocktail:latest ls /work_dir/data/D8.sorted.bam `

**Comment by 815325223** [comment]
Yes, I did see its existence.
$ docker run --rm -u container_R -v /D8:/work_dir/data -v /Container:/work_dir/write marghoob/rnacocktail:latest ls /work_dir/data/D8.sorted.bam
/work_dir/data/D8.sorted.bam

**Comment by msahraeian** [comment]
Can you try the following command, so that I can see full details about you bam file:

`docker run --rm -u container_R -v /D8:/work_dir/data -v /Container:/work_dir/write rnacocktail:latest ls -al /work_dir/data/D8.sorted.bam`

**Comment by 815325223** [comment]
# docker run --rm -u container_R -v /D8:/work_dir/data -v /Container:/work_dir/write rnacocktail:latest ls -la /work_dir/data/D8.sorted.bam
lrwxrwxrwx 1 1012 NGS-BI-RNA 105 Feb 26 06:22 /work_dir/data/D8.sorted.bam -> /D8/D8.sorted.bam
# id container_R
uid=3001(container_R) gid=1001(NGS) groups=1001(NGS),1305(NGS-BI-RNA)

**Comment by 815325223** [comment]
Thank you for your continued help

**Comment by msahraeian** [comment]
I think the problem is the symlink. You should have absolute path in docker. 
Can you check `ls -al /D8/D8.sorted.bam` in your host system?

**Comment by 815325223** [comment]
It's works. The data is indeed a soft link. But I have a new problem again. “Error: Unable to access jarfile GenomeAnalysisTK.jar” I checked the dockerfile and did not install GATK, right?

**Comment by msahraeian** [comment]
Sounds good. Yes, GATK is not part of our docker. 
You can download GATK 3.5 at:
https://software.broadinstitute.org/gatk/download/archive
https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.5-0-g36282e4

and provide the jar file as input like `--gatk /path/to/GenomeAnalysisTK.jar `
