### ISSUE TITLE
Error in run_editing STEP 10

### ISSUE THREAD

**Issue by thestarocean** [bioinform/rnacocktail#15]
Currently I am using RNAcocktail for RNA editing sites identification. All procedure went smoothly until STEP 10, with log showing as follows: 
INFO 2019-04-09 11:37:47,149 src.run_editing      --------------------------STEP 9--------------------------
INFO 2019-04-09 11:37:47,150 src.run_editing      Task: Rerun GIREMI for 1351 
INFO 2019-04-09 11:37:47,150 src.run_editing      Running "bash -c cd /cloud/data/zxcai/soft/giremi && giremi  -f /cloud/data/zxcai/ref/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa -l /cloud/data/zxcai/RNAcocktail_test/giremi/1351/SNV_annotated_filtered.bed -o /cloud/data/zxcai/RNAcocktail_test/giremi/1351/giremi_out.txt /cloud/data/zxcai/RNAcocktail_test/giremi/1351/alignments.pos_sorted.bam" 
INFO 2019-04-09 12:28:29,244 src.run_editing      Returned code 1 (3042.03 seconds)
INFO 2019-04-09 12:28:29,252 src.utils            Creating directory /cloud/data/zxcai/RNAcocktail_test/out/giremi/1351
INFO 2019-04-09 12:28:29,287 src.run_editing      --------------------------STEP 10--------------------------
INFO 2019-04-09 12:28:29,296 src.run_editing      GIREMI failed!
INFO 2019-04-09 12:28:29,296 src.utils            Run log is saved in /cloud/data/zxcai/RNAcocktail_test/logs/run-editing-20190409-113746.log
INFO 2019-04-09 12:28:29,296 src.utils            All Done!

And when I check the work dir for output files generated during the analysis, I discovered that  giremi_out.txt existed, but not giremi_out.txt.res (which should be copied to output dir in STEP 10). So I try to locate where this problem comes from,  and could not find where giremi_out.txt.res is generated according to run_editing.py.
My guess is that when rerun Giremi to remove N variants, maybe the output should be giremi_out.txt.res?

**Comment by thestarocean** [comment]
I realized that according to giremi documents, giremi.pl did produce *.res files. However, in defaults.py, GIREMI was assigned with "giremi". So my guess is that this value should be "giremi.pl"? So it could use the R script to predict RNA editing and output *.res files?

**Comment by thestarocean** [comment]
OK, I figure out that I was using giremi.zip downloaded from https://www.ibp.ucla.edu/research/xiao/GIREMI.html. Apparently, it's a bit different with github version, because it uses giremi.pl while github version uses only "giremi".
Sorry for bothering you.

**Comment by msahraeian** [comment]
@thestarocean happy to see your interest in RNACocktail. That's great that you have already resolved the issue.
