### ISSUE TITLE
IOError: [Errno 36] File name too long: 

### ISSUE THREAD

**Issue by Shawn-Xu** [bioinform/rnacocktail#5]
I have 80 samples for "--sample" parameters of "run_rnacocktail.py diff".
And the I got the error info:
**IOError: [Errno 36] File name too long:**
I found it because rnacoktail will use all the sample names to create the log name. However, Popular file system Linux(ext4) has a  filename length limitof 255 chars. can you have some alternative solution?
Appreciate it!

**Comment by msahraeian** [comment]
Hi @Shawn-Xu,

Thanks for your interest in RNACocktail.
I fixed the script to avoid adding sample names to log name. Please try again. 
It is fixed in #6.

**Comment by Shawn-Xu** [comment]
Hi @msahraeian ,
Thanks for your prompt response.   it works well now.
