### ISSUE TITLE
hisat2_jun2bed.py error

### ISSUE THREAD

**Issue by nongbaoting** [bioinform/rnacocktail#7]
when I ran rnacocktail with align mode, i got an error below. 
```
Traceback (most recent call last):
  File "/usr/local/bin/hisat2_jun2bed.py", line 32, in <module>
    int_start =  int(locus_ls[1])-51
ValueError: invalid literal for int() with base 10: 'ctg9'
```
and then I ckecked this error carefully, I found that when my input chromosome name contained seporater ` "_"`,  the program will throw out an error above! consider many organsim's chromosome names contain seporater '_' especially the new assembly organism genome, i recommend you shoud change line 23 `locus = "_".join([line_list[0],leftpos,rightpos,line_list[3]])` to `locus = "__".join([line_list[0],leftpos,rightpos,line_list[3]])` and line 30 `locus_ls = locus.split("_")` to `locus_ls = locus.split("__")` in script 'hisat2_jun2bed.py' , or change another seporater . that will work properly!

sincerely

**Comment by msahraeian** [comment]
Hi @nongbaoting,

Thanks for your interest in RNACocktail.
I fixed the script to avoid this confusion in chromosome names. Please try again.
It is fixed in #8.
