### ISSUE TITLE
Cannot start run_rnacocktail.py

### ISSUE THREAD

**Issue by hhg7** [bioinform/rnacocktail#9]
I'm just trying to get started with RNAcocktail, but I don't see how I can get this started, I can't even get the help menu.  I don't see how to get this installed and I don't see anything about this in the README files.

```
703404669@bioitutil2:/illumina/runs/RNASeq/rnacocktail-0.2.1/scripts$ ./run_rnacocktail.py 
Traceback (most recent call last):
  File "./run_rnacocktail.py", line 5, in <module>
    from src.main import run_pipeline
ImportError: No module named src.main
703404669@bioitutil2:/illumina/runs/RNASeq/rnacocktail-0.2.1/scripts$ ./run_rnacocktail.py -h
Traceback (most recent call last):
  File "./run_rnacocktail.py", line 5, in <module>
    from src.main import run_pipeline
ImportError: No module named src.main
703404669@bioitutil2:/illumina/runs/RNASeq/rnacocktail-0.2.1/scripts$
```

**Comment by marghoob** [comment]
@hhg7 Thanks for filing this issue. Did you try installing using `pip`? Please have a look at https://bioinform.github.io/rnacocktail/ (have a look at the _Installing RNACocktail_ section).

**Comment by hhg7** [comment]
@marghoob yes, pip is installed.  Thanks, my goof.  I thought this would install like most .tar.gz files.

**Comment by marghoob** [comment]
No worries, @hhg7. I am glad you were finally able to install it.
